/* eslint-disable */
/* tslint:disable */
/*
 * -------------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                              ##
 * ## DO NOT EDIT THIS FILE DIRECTLY                                                  ##
 * ##                                                                                 ##
 * ## AUTHOR: Stef Buurman                                                            ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * -------------------------------------------------------------------------------------
 */
import { request } from '../generated/http-client';
import type { RequestParams } from '../generated/http-client';
import type {
  ApiKeyResponse,
  HttpValidationProblemDetails,
  ProblemDetails,
} from '../generated/data-contracts';
import { handleApiResponse } from 'typedapi-client-helpers';
import type { ApiMethodOptions, ApiResult } from 'typedapi-client-helpers';
import {
  handleGoodResult as typedApiDefaultSuccessHandler,
  handleErrors as typedApiDefaultErrorHandler,
  unknownErrorMessage as typedApiDefaultErrorMessage,
} from '../../defaultApiFunctions';

/**
 * No description
 *
 * @tags ApiKey
 * @name createApiKey
 * @request GET:/api/create-api-key
 */
export async function createApiKey(
  options: ApiMethodOptions<
    ApiKeyResponse,
    HttpValidationProblemDetails | ProblemDetails,
    RequestParams
  > = {},
): Promise<
  ApiResult<ApiKeyResponse, HttpValidationProblemDetails | ProblemDetails>
> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<
    ApiKeyResponse,
    HttpValidationProblemDetails | ProblemDetails
  >(
    () =>
      request<ApiKeyResponse, HttpValidationProblemDetails | ProblemDetails>({
        ...params,
        path: `/api/create-api-key`,
        method: 'GET',
        format: 'json',
      }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}
