/* eslint-disable */
/* tslint:disable */
/*
 * -------------------------------------------------------------------------------------
 * ## THIS FILE WAS GENERATED BY typedapi-client-helpers                              ##
 * ## DO NOT EDIT THIS FILE DIRECTLY                                                  ##
 * ##                                                                                 ##
 * ## AUTHOR: Stef Buurman                                                            ##
 * ## SOURCE: https://github.com/Stef-Buurman/TypedApi/tree/main/npm/typed-api-client ##
 * -------------------------------------------------------------------------------------
 */
import { ContentType, request } from "../generated/http-client";
import type { RequestParams } from "../generated/http-client";
import type {
  Contact,
  ContactDeleteContactDELETEApiContactIdParams,
  HttpValidationProblemDetails,
  ProblemDetails,
} from "../generated/data-contracts";
import { handleApiResponse } from "typedapi-client-helpers";
import type { ApiMethodOptions, ApiResult } from "typedapi-client-helpers";
import { handleGoodResult as typedApiDefaultSuccessHandler, handleErrors as typedApiDefaultErrorHandler, unknownErrorMessage as typedApiDefaultErrorMessage } from "../../defaultApiFunctions";

/**
 * No description
 *
 * @tags Contact
 * @name Contact_UploadContact_POST_api_contact
 * @request POST:/api/contact
 */
export async function contactUploadContactPOSTApiContact(
  data: Contact,
  options: ApiMethodOptions<void, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<void, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<void, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<void, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/contact`,
      method: "POST",
      body: data,
      type: ContentType.Json,
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Contact
 * @name Contact_GetContacts_GET_api_contacts
 * @request GET:/api/contacts
 */
export async function contactGetContactsGETApiContacts(
  options: ApiMethodOptions<Contact[], HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<Contact[], HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<Contact[], HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<Contact[], HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/contacts`,
      method: "GET",
      format: "json",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}

/**
 * No description
 *
 * @tags Contact
 * @name Contact_DeleteContact_DELETE_api_contact_id
 * @request DELETE:/api/contact/{id}
 */
export async function contactDeleteContactDELETEApiContactId(
  pathParams: ContactDeleteContactDELETEApiContactIdParams,
  options: ApiMethodOptions<void, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails, RequestParams> = {}
): Promise<ApiResult<void, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>> {
  const { onSuccess, onError, params = {} } = options;

  return handleApiResponse<void, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>(
    () => request<void, HttpValidationProblemDetails | ProblemDetails | HttpValidationProblemDetails>({
      ...params,
      path: `/api/contact/${encodeURIComponent(String(pathParams["id"]))}`,
      method: "DELETE",
    }),
    {
      onSuccess: onSuccess ?? typedApiDefaultSuccessHandler,
      onError: onError ?? typedApiDefaultErrorHandler,
      fallbackErrorMessage: typedApiDefaultErrorMessage,
    },
  );
}
